#!/usr/bin/env python3
"""Generate the strategy build of ICT Fractal Models from the indicator source.

The indicator is the single source of truth. Two markers drive the build:

* ``//@S <code>``  – strategy-only line: the marker is stripped, the code kept.
* ``<code> // @ind`` – indicator-only line: commented out in the strategy build.

Usage:
    python3 tools/build_strategy.py          # write the strategy file
    python3 tools/build_strategy.py --check  # exit 1 if it is out of date
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "ICT_Fractal_Models.pine"
OUT = ROOT / "ICT_Fractal_Models_Strategy.pine"

HEADER = "// GENERATED by tools/build_strategy.py from ICT_Fractal_Models.pine. Do not edit.\n"


def build(src: str) -> str:
    out = []
    for line in src.splitlines():
        if line.startswith("//@S "):
            out.append(line[len("//@S "):])
        elif line.rstrip().endswith("// @ind"):
            out.append("// " + line)
        else:
            out.append(line)
    body = "\n".join(out) + "\n"
    # keep //@version on the first line, as Pine requires
    first, rest = body.split("\n", 1)
    return first + "\n" + HEADER + rest


def main() -> int:
    built = build(SRC.read_text(encoding="utf-8"))
    if "--check" in sys.argv[1:]:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != built:
            print(f"{OUT.name} is out of date: run python3 tools/build_strategy.py")
            return 1
        print(f"{OUT.name} is up to date")
        return 0
    OUT.write_text(built, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
